---
name: Git commit
description: Git commit

inputs:
  GITHUB_TOKEN:
    description: Github token
    required: true

runs:
  using: composite
  steps:
    - name: 'commit update'
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        echo "Start."
        git config --global user.email github-actions[bot]@users.noreply.github.com
        git config --global user.name github-actions[bot]
        git config pull.rebase false
        git checkout main
        git pull origin main
        git add .
        git commit -m 'Automated documentation update [skip ci]' || echo "No changes to commit"

        if ! git push origin main; then
          echo "Push failed, trying git pull --rebase and push again..."
          git pull --rebase origin main
          git push origin main
        fi
