---
name: Git commit
description: Git commit

inputs:
  GITHUB_TOKEN:
    description: Github token
    required: true

runs:
  using: composite
  steps:
    - name: 'commit update'
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        git config --global user.email github-actions[bot]@users.noreply.github.com
        git config --global user.name github-actions[bot]
        git config pull.rebase false

        git fetch origin
        git checkout main
        git reset --hard origin/main

        git add .
        git commit -m 'Automated documentation update [skip ci]' || echo "No changes to commit"

        if ! git push --force-with-lease origin main; then
          echo "Push failed — remote main may have changed."
          echo "Skipping force push to avoid overwriting someone else's work."
          exit 1
        fi
