# syntax=docker.io/docker/dockerfile:1

FROM public.ecr.aws/dev1-sg/alpine/node:24.5.0-3.21 AS base

ARG AWSCDK_VERSION

USER root

RUN apk add --no-cache docker-cli

WORKDIR /build

FROM base AS final

RUN npm i -g cdk@${AWSCDK_VERSION} \
    && rm -rf /var/cache/apk/*
