---
name: Docs readme update

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
  GH_TOKEN: ${{secrets.GH_TOKEN}}
  TZ: Asia/Singapore

jobs:
  run-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set shell options
        run: set -euxo pipefail

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: docs/requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          role-session-name: aws-oidc-${{ github.repository.name }}-${{ github.run_id }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to AWS ECR Public Registry
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2

      - run: pip install -r requirements.txt
        working-directory: docs

      - name: Run Python script
        working-directory: docs
        run: python3 query-ecr-public-repos.py

      - name: 'commit update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Start."
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git config pull.rebase false
          git checkout main
          git pull origin main
          git add readme.md
          git commit -m 'Automated documentation update [skip ci]' || echo "No changes to commit"

          if ! git push origin main; then
            echo "Push failed, trying git pull --rebase and push again..."
            git pull --rebase origin main
            git push origin main
          fi
