---
name: PR Dependabot tests

on:
  pull_request:
    paths:
      - tests/*
      - go.mod
      - go.sum
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

env:
  DOCKER_IMAGE: ubuntu
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  dependabot-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set shell options
        run: set -euxo pipefail

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'
      - run: go version

      - name: Run go tests
        run: |
          go test -run 'TestContainersGo.*' ./... -v

      - name: Setup Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ env.GH_TOKEN }}

      - name: Auto-merge for Dependabot PR
        run: gh pr merge --auto --rebase ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
