---
name: Docs readme update

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Singapore

jobs:
  run-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup python
        uses: ./.github/actions/setup-python
        with:
          AWS_OIDC_ROLE_ARN: ${{ env.AWS_OIDC_ROLE_ARN }}

      - run: python3 scripts/generate_main_readme.py

      - run: python3 scripts/generate_image_readme.py

      - name: Git commit
        uses: ./.github/actions/git-commit
        with:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
